services:
  - type: web
    name: influencerbase-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python main.py
    rootDir: .
